/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glcc;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author fatim
 */
public class DescriptionInterface extends javax.swing.JFrame {

    /**
     * Creates new form INTERFACE
     */
    public DescriptionInterface() {
        initComponents();
        setDefaultCloseOperation(DescriptionInterface.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Etapes = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Etapes2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        NomRecette = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        NomRecette3 = new javax.swing.JLabel();
        NomRecette1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TotalFruit = new javax.swing.JLabel();
        TotalFruit1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        NomRecette4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listeRecap1 = new javax.swing.JList<>();

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 100));

        Etapes.setEditable(false);
        Etapes.setColumns(20);
        Etapes.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Etapes.setForeground(new java.awt.Color(0, 102, 0));
        Etapes.setLineWrap(true);
        Etapes.setRows(5);
        Etapes.setText("1-Ajouter deux boules de glace chocolat.\n2-Parsemer de praliné et noisettes.\n3-Servir avec un filet de chocolat fondu.\n");
        Etapes.setMaximumSize(new java.awt.Dimension(30000, 80000));
        Etapes.setMinimumSize(new java.awt.Dimension(300, 80));
        jScrollPane1.setViewportView(Etapes);

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setToolTipText("");
        jScrollPane3.setPreferredSize(new java.awt.Dimension(450, 100));

        Etapes2.setEditable(false);
        Etapes2.setColumns(20);
        Etapes2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Etapes2.setForeground(new java.awt.Color(0, 102, 0));
        Etapes2.setLineWrap(true);
        Etapes2.setRows(5);
        Etapes2.setText("-Lait entier\n-Crème fraîche (25%)\n-Sucre\n-Jaune d'œuf\n-Extrait naturel de vanille Bourbon\n-Épaississant : gomme de guar\nÉmulsifiant : lécithine de soja\n");
        Etapes2.setMaximumSize(new java.awt.Dimension(30000, 80000));
        Etapes2.setMinimumSize(new java.awt.Dimension(300, 80));
        jScrollPane3.setViewportView(Etapes2);

        jPanel3.setForeground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jList2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(jList2);

        NomRecette.setFont(new java.awt.Font("Eunjin Nakseo", 1, 24)); // NOI18N
        NomRecette.setForeground(new java.awt.Color(0, 51, 204));
        NomRecette.setText("Allergènes et informations :  ");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane7.setViewportView(jTextArea2);

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(jList1);

        NomRecette3.setFont(new java.awt.Font("Eunjin Nakseo", 1, 24)); // NOI18N
        NomRecette3.setForeground(new java.awt.Color(0, 0, 204));
        NomRecette3.setText("Ingrédients : ");

        NomRecette1.setFont(new java.awt.Font("Eunjin Nakseo", 1, 24)); // NOI18N
        NomRecette1.setForeground(new java.awt.Color(255, 0, 0));
        NomRecette1.setText("Information sur la glace");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Prix:");

        TotalFruit.setFont(new java.awt.Font("Eunjin Nakseo", 1, 18)); // NOI18N
        TotalFruit.setForeground(new java.awt.Color(0, 0, 153));
        TotalFruit.setText("€ ");

        TotalFruit1.setFont(new java.awt.Font("Eunjin Nakseo", 1, 18)); // NOI18N
        TotalFruit1.setForeground(new java.awt.Color(0, 0, 153));
        TotalFruit1.setText("0,0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalFruit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(TotalFruit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TotalFruit1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 102));

        NomRecette4.setBackground(new java.awt.Color(255, 204, 102));
        NomRecette4.setFont(new java.awt.Font("Eunjin Nakseo", 1, 36)); // NOI18N
        NomRecette4.setForeground(new java.awt.Color(204, 0, 0));
        NomRecette4.setText("Description : ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomRecette4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomRecette4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(NomRecette3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(NomRecette))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NomRecette1))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(NomRecette1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomRecette, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomRecette3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        listeRecap1.setFont(new java.awt.Font("Eunjin Nakseo", 0, 15)); // NOI18N
        listeRecap1.setForeground(new java.awt.Color(189, 98, 199));
        listeRecap1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cette glace contient des produits laitiers (comme le lait et la crème), ", "des œufs (présents dans le jaune d'œuf),", " et des dérivés de soja (comme la lécithine utilisée comme émulsifiant). ", "Peut contenir des traces de fruits à coque et d'arachides. ", "Sans gluten et adaptée aux végétariens." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeRecap1.setMaximumSize(new java.awt.Dimension(60, 150));
        listeRecap1.setMinimumSize(new java.awt.Dimension(60, 150));
        listeRecap1.setPreferredSize(new java.awt.Dimension(60, 150));
        listeRecap1.setRequestFocusEnabled(false);
        listeRecap1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(listeRecap1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 510, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Méthode pour afficher les détails dynamiquement
    public void afficherDetails(String titre, String description, List<String> ingredients, List<String> allergenes, String valeursEnergetiques, double prix) {
        // Mettre à jour les textes et les listes
        NomRecette1.setText(titre);
        jTextArea2.setText(description);

        DefaultListModel<String> modelIngredients = new DefaultListModel<>();
        for (String ingredient : ingredients) {
            modelIngredients.addElement(ingredient);
        }
        jList1.setModel(modelIngredients);

        DefaultListModel<String> modelAllergenes = new DefaultListModel<>();
        for (String allergene : allergenes) {
            modelAllergenes.addElement(allergene);
        }
        jList2.setModel(modelAllergenes);

        Etapes2.setText(valeursEnergetiques);
        TotalFruit1.setText(String.format("%.2f", prix));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescriptionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescriptionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescriptionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescriptionInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescriptionInterface().setVisible(true);
            }
            
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Etapes;
    private javax.swing.JTextArea Etapes2;
    private javax.swing.JLabel NomRecette;
    private javax.swing.JLabel NomRecette1;
    private javax.swing.JLabel NomRecette3;
    private javax.swing.JLabel NomRecette4;
    private javax.swing.JLabel TotalFruit;
    private javax.swing.JLabel TotalFruit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList<String> listeRecap1;
    // End of variables declaration//GEN-END:variables
}
