package glcc;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.io.File;
import java.awt.Image;


/**
 *
 * @author adlane
 */
public class GlaceInterface extends javax.swing.JFrame {

    /**
     * Creates new form glace
     */
     public GlaceInterface() {
        initComponents();
        panierInterface = new PanierInterface(this); // Crée l'interface panier
        chargerImagesBoutons();

    }
     
        private boolean baseCree = false; // Indique si un pot ou un cornet a été créé
        private boolean glaceTerminee=false;
        private Glace glaceEnCours; // Glace actuellement créée
        private int nbBoules = 0;  // Nombre de boules ajoutées
        private static final int MAX_BOULES = 4; // Limite des boules
        private PanierInterface panierInterface = new PanierInterface(this); // Instance unique de panier
        private double totalPrix = 0.0; // Total des prix des glaces ajoutées

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        voirPanier = new javax.swing.JButton();
        prix = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        ajouterPanier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        creerPot = new javax.swing.JButton();
        creerCornet = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Fraise = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Caramel = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Vanille = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        Pistache = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        Chocolat = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        Chantilly = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        NappageFraise = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        NappageCaramel = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        NappageChocolat = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Bienvenue ");

        voirPanier.setBackground(new java.awt.Color(204, 0, 204));
        voirPanier.setForeground(new java.awt.Color(255, 255, 0));
        voirPanier.setText("Voir mon panier ");
        voirPanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirPanierActionPerformed(evt);
            }
        });

        prix.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prix.setText("Total : 00,00€ ");

        messages.setColumns(20);
        messages.setRows(5);
        jScrollPane1.setViewportView(messages);

        ajouterPanier.setBackground(new java.awt.Color(0, 204, 51));
        ajouterPanier.setText("Ajouter au panier");
        ajouterPanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterPanierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prix)
                            .addComponent(ajouterPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voirPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ajouterPanier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voirPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prix)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        jPanel4.setLayout(new java.awt.GridLayout(1, 6));

        creerPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerPotActionPerformed(evt);
            }
        });
        jPanel4.add(creerPot);

        creerCornet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerCornetActionPerformed(evt);
            }
        });
        jPanel4.add(creerCornet);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 6));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fraise.setPreferredSize(new java.awt.Dimension(100, 160));
        Fraise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FraiseActionPerformed(evt);
            }
        });
        jPanel7.add(Fraise, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 80));

        jButton14.setText("Description");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 96, 20));

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Caramel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaramelActionPerformed(evt);
            }
        });
        jPanel8.add(Caramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 80));

        jButton16.setText("Description");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 96, 20));

        jPanel5.add(jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vanille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanilleActionPerformed(evt);
            }
        });
        jPanel9.add(Vanille, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 80));

        jButton18.setText("Description");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 20));

        jPanel5.add(jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pistache.setToolTipText("");
        Pistache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PistacheActionPerformed(evt);
            }
        });
        jPanel10.add(Pistache, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 80));

        jButton20.setText("Description");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 96, 20));

        jPanel5.add(jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chocolat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolatActionPerformed(evt);
            }
        });
        jPanel11.add(Chocolat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 96, 80));

        jButton22.setText("Description");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 96, 20));

        jPanel5.add(jPanel11);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 4));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Chantilly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChantillyActionPerformed(evt);
            }
        });
        jPanel12.add(Chantilly, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        jButton24.setText("Description");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 20));

        jPanel6.add(jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NappageFraise.setToolTipText("");
        NappageFraise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappageFraiseActionPerformed(evt);
            }
        });
        jPanel13.add(NappageFraise, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        jButton26.setText("Description");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 20));

        jPanel6.add(jPanel13);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NappageCaramel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappageCaramelActionPerformed(evt);
            }
        });
        jPanel14.add(NappageCaramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        jButton28.setText("Description");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 20));

        jPanel6.add(jPanel14);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NappageChocolat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NappageChocolatActionPerformed(evt);
            }
        });
        jPanel15.add(NappageChocolat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        jButton30.setText("Description");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 120, 20));

        jPanel6.add(jPanel15);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerPotActionPerformed
    if (!baseCree) {
        glaceEnCours = new GlacePot();
        baseCree = true;

        // Activer les boutons de goûts et nappages
        activerBoutonsGoutsEtNappages(true);

        // Désactiver les boutons "Créer pot" et "Créer cornet"
        creerPot.setEnabled(false);
        creerCornet.setEnabled(false);
        mettreAJourPrix();
        afficherMessage("Pot créé.\n Ajoutez vos boules et nappages !");
    }
    }//GEN-LAST:event_creerPotActionPerformed

    private void creerCornetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerCornetActionPerformed
     if (!baseCree) {
        glaceEnCours = new GlaceCornet();
        baseCree = true;

        // Activer les boutons de goûts et nappages
        activerBoutonsGoutsEtNappages(true);

        // Désactiver les boutons "Créer pot" et "Créer cornet"
        creerPot.setEnabled(false);
        creerCornet.setEnabled(false);
        mettreAJourPrix();

       afficherMessage("Cornet créé. Ajoutez vos boules et nappages !");
    }
    }//GEN-LAST:event_creerCornetActionPerformed

    private void FraiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FraiseActionPerformed
            ajouterGout("Fraise");

    }//GEN-LAST:event_FraiseActionPerformed

    private void CaramelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaramelActionPerformed
            ajouterGout("Caramel");

    }//GEN-LAST:event_CaramelActionPerformed

    private void VanilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanilleActionPerformed
            ajouterGout("Vanille");
    }//GEN-LAST:event_VanilleActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
                    if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

     Vanille  vanille = new  Vanille(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Glace  Vanille", 
        "Une boule de glace rafraîchissante à la  vanille, délicatement sucrée.",
         vanille.getIngredients(),
         vanille.getAllergenes(),
        
        vanille.getValeursEnergetiques(),
        vanille.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void PistacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PistacheActionPerformed
            ajouterGout("Pistache");
    }//GEN-LAST:event_PistacheActionPerformed

    private void ChantillyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChantillyActionPerformed
            ajouterNappage("Chantilly");
    }//GEN-LAST:event_ChantillyActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
                   if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

     Pistache  pistache = new  Pistache(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Glace  Pistache", 
        "Une boule de glace rafraîchissante à la  pistache, délicatement sucrée.",
         pistache.getIngredients(),
        pistache.getAllergenes(),
        
        pistache.getValeursEnergetiques(),
        pistache.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
                   if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

     Chocolat chocolat = new Chocolat(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Glace  Chocolat", 
        "Une boule de glace rafraîchissante à la  chocolat, délicatement sucrée.",
        chocolat.getIngredients(),
        chocolat.getAllergenes(),
        
        chocolat.getValeursEnergetiques(),
        chocolat.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
       if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

    Chantilly chantilly = new Chantilly(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Chantilly", 
        "Un délicieux supplément de chantilly pour votre glace.",
        chantilly.getIngredients(),
        chantilly.getAllergenes(),
        chantilly.getValeursEnergetiques(),
        chantilly.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
                     if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

    NappageFraise Nfraise = new NappageFraise(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Nappage a la Fraise ", 
        "Une boule de glace rafraîchissante avec un supplément fraise , délicatement sucrée.",
        Nfraise.getIngredients(),
        Nfraise.getAllergenes(),
        
        Nfraise.getValeursEnergetiques(),
        Nfraise.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
                          if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

    NappageCaramel Ncaramel = new NappageCaramel(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Nappage Carmel", 
        "Une boule de glace rafraîchissante avce un supplément caramel, délicatement sucrée.",
        Ncaramel.getIngredients(),
        Ncaramel.getAllergenes(),
        
        Ncaramel.getValeursEnergetiques(),
        Ncaramel.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
                         if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

    NappageChocolat Nchocolat = new NappageChocolat(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Nappage Chocolat", 
        "Une boule de glace rafraîchissante avce un supplément chocolat, délicatement sucrée.",
        Nchocolat.getIngredients(),
        Nchocolat.getAllergenes(),
        
        Nchocolat.getValeursEnergetiques(),
        Nchocolat.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void NappageChocolatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappageChocolatActionPerformed
            ajouterNappage("Chocolat");
    }//GEN-LAST:event_NappageChocolatActionPerformed

    private void ChocolatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolatActionPerformed
            ajouterGout("Chocolat");
    }//GEN-LAST:event_ChocolatActionPerformed

    private void NappageFraiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappageFraiseActionPerformed
            ajouterNappage("Fraise");
    }//GEN-LAST:event_NappageFraiseActionPerformed

    private void NappageCaramelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NappageCaramelActionPerformed
            ajouterNappage("Caramel");
    }//GEN-LAST:event_NappageCaramelActionPerformed
            

    private void ajouterPanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterPanierActionPerformed
         if (glaceEnCours == null) {
        afficherMessage("Aucune base n'a été créée. Veuillez choisir un pot ou un cornet.");
        return;
    }

    if (nbBoules == 0) {
        afficherMessage("Vous devez ajouter au moins une boule avant d'ajouter la glace au panier !");
        return;
    }

    // Vérifiez que la glace est "terminée" en validant sa description
    String descriptionGlace = glaceEnCours.getDesc();
    if (descriptionGlace == null || descriptionGlace.isEmpty() || descriptionGlace.contains("non terminée")) {
        afficherMessage("La glace n'est pas correctement construite. Ajoutez des boules et/ou nappages.");
        return;
    }

    // Ajouter la glace au panier
    panierInterface.ajouterGlaceAuPanier(glaceEnCours);

    // Ajouter le prix de la glace au total cumulé
    totalPrix += glaceEnCours.getPrix();

    // Mettre à jour l'affichage du total
    mettreAJourTotal();

    afficherMessage("Glace ajoutée au panier : " + descriptionGlace);

    // Réinitialiser pour permettre une nouvelle création
    glaceEnCours = null;
    nbBoules = 0;
    baseCree = false;

    creerPot.setEnabled(true);
    creerCornet.setEnabled(true);
    activerBoutonsGoutsEtNappages(false);
    }//GEN-LAST:event_ajouterPanierActionPerformed
                                       

                                  

    
    private void voirPanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirPanierActionPerformed
        if (panierInterface == null) {
            panierInterface = new PanierInterface(this); // Crée l'interface panier si elle n'existe pas encore
        }

        panierInterface.rechargerPanier(); // Recharge les données du panier
        panierInterface.setVisible(true); // Affiche l'interface panier
    }//GEN-LAST:event_voirPanierActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                            if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

     Caramel  caramel = new  Caramel(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Glace  Caramel", 
        "Une boule de glace rafraîchissante au Caramel, délicatement sucrée.",
         caramel.getIngredients(),
        caramel.getAllergenes(),
        
        caramel.getValeursEnergetiques(),
        caramel.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                            if (glaceEnCours == null) {
        afficherMessage("Créez une base (pot ou cornet) avant d'ajouter un ingrédient.");
        return;
    }

     Fraise  fraise = new  Fraise(glaceEnCours);

    // Crée une nouvelle instance de INTERFACE
    DescriptionInterface detailsInterface = new DescriptionInterface();

    // Remplit l'interface avec les détails
    detailsInterface.afficherDetails(
        "Glace  Fraise", 
        "Une boule de glace rafraîchissante à la  fraise, délicatement sucrée.",
         fraise.getIngredients(),
        fraise.getAllergenes(),
        
        fraise.getValeursEnergetiques(),
        fraise.getPrix()
    );

    // Affiche l'interface
    detailsInterface.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    
    
    
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlaceInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Caramel;
    private javax.swing.JButton Chantilly;
    private javax.swing.JButton Chocolat;
    private javax.swing.JButton Fraise;
    private javax.swing.JButton NappageCaramel;
    private javax.swing.JButton NappageChocolat;
    private javax.swing.JButton NappageFraise;
    private javax.swing.JButton Pistache;
    private javax.swing.JButton Vanille;
    private javax.swing.JButton ajouterPanier;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton creerCornet;
    private javax.swing.JButton creerPot;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messages;
    private javax.swing.JLabel prix;
    private javax.swing.JButton voirPanier;
    // End of variables declaration//GEN-END:variables

    
    private void ajouterGout(String gout) {
    if (baseCree && nbBoules < MAX_BOULES) {
        switch (gout) {
            case "Vanille":
                glaceEnCours = new Vanille(glaceEnCours);
                break;
            case "Fraise":
                glaceEnCours = new Fraise(glaceEnCours);
                break;
            case "Caramel":
                glaceEnCours = new Caramel(glaceEnCours);
                break;
            case "Pistache":
                glaceEnCours = new Pistache(glaceEnCours);
                break;
            case "Chocolat":
                glaceEnCours = new Chocolat(glaceEnCours);
                break;    
            default:
                afficherMessage("Goût non valide !");
                return;
        }
        nbBoules++;
        afficherMessage("Boule ajoutée : " + gout + " (" + nbBoules + "/" + MAX_BOULES + ")");
        mettreAJourPrix(); // Mettre à jour le prix
    } else if (nbBoules >= MAX_BOULES) {
        afficherMessage("Vous ne pouvez pas ajouter plus de " + MAX_BOULES + " boules.");
    }
}

    
    
    private void ajouterNappage(String nappage) {
    if (baseCree) {
        switch (nappage) {
            case "Caramel":
                glaceEnCours = new NappageCaramel(glaceEnCours);
                break;
            case "Fraise":
                glaceEnCours = new NappageFraise(glaceEnCours);
                break;
            case "Chocolat":
                glaceEnCours = new NappageChocolat(glaceEnCours);
                break;
            case "Chantilly":
                glaceEnCours = new Chantilly(glaceEnCours);
                break;
            default:
                afficherMessage("Nappage non valide !");
                return;
        }
        afficherMessage("Nappage ajouté : " + nappage);
        mettreAJourPrix(); // Mettre à jour le prix
    } else {
        afficherMessage("Créez une base avant d'ajouter un nappage.");
    }
}
    
  

    
    private void activerBoutonsGoutsEtNappages(boolean activer) {
    Chocolat.setEnabled(activer);
    Vanille.setEnabled(activer);
    Fraise.setEnabled(activer);
    Caramel.setEnabled(activer);
    Pistache.setEnabled(activer);

    Chantilly.setEnabled(activer);
    NappageCaramel.setEnabled(activer);
    NappageChocolat.setEnabled(activer);
    NappageFraise.setEnabled(activer);
}
    private void afficherDescription(String message) {
    // Ajouter le message à la zone de texte
    messages.append(message + "\n");
    // Faire défiler automatiquement vers le bas pour afficher le dernier message
    messages.setCaretPosition(messages.getDocument().getLength());
}

    private void afficherDetailsIngredient(Ingredient ingredient) {
    afficherDescription("Description : " + ingredient.getDesc() + "\n"
        + "Prix additionnel : " + String.format("%.2f", ingredient.getPrix() - glaceEnCours.getPrix()) + "€\n"
        + "Ingrédients : " + String.join(", ", ingredient.getIngredients()) + "\n"
        + "Allergènes : " + String.join(", ", ingredient.getAllergenes()) + "\n"
        + "Valeurs énergétiques : " + ingredient.getValeursEnergetiques());
}
    
    private void afficherMessage(String message) {
    messages.append(message + "\n"); // Ajouter le message avec un retour à la ligne
    messages.setCaretPosition(messages.getDocument().getLength()); // Faire défiler automatiquement vers le bas
}

private void mettreAJourPrix() {
    if (glaceEnCours != null) {
        double price = glaceEnCours.getPrix();
        prix.setText("Prix : " + String.format("%.2f", price) + " €");
    } else {
        prix.setText("Prix : 0,00 €");
    }
}

public void mettreAJourTotal() {
    prix.setText("Total : " + String.format("%.2f", totalPrix) + " €");
}

public void mettreAJourPrixPrincipal(double prixTotal) {
    prix.setText("Total : " + String.format("%.2f", prixTotal) + " €");
}

public void resetTotalPrix() {
    totalPrix = 0.0; // Réinitialise la valeur interne
    mettreAJourPrixPrincipal(0.0); // Réinitialise l'affichage
}

public void resetMessages() {
    messages.setText(""); // Vider la zone de texte
}

private ImageIcon redimensionnerImage(String chemin, int largeur, int hauteur) {
    ImageIcon icon = new ImageIcon(chemin);
    Image img = icon.getImage();
    Image imgRedim = img.getScaledInstance(largeur, hauteur, Image.SCALE_SMOOTH);
    return new ImageIcon(imgRedim);
}


private void chargerImagesBoutons() {
    try {
        // Charger les images pour les goûts
        Vanille.setIcon(redimensionnerImage("images/vanille.png", 90, 70));
        Fraise.setIcon(redimensionnerImage("images/fraise.jpg", 90, 70));
        Caramel.setIcon(redimensionnerImage("images/caramel.jpg", 90, 70));
        Pistache.setIcon(redimensionnerImage("images/pistache.jpg", 90, 70));
        Chocolat.setIcon(redimensionnerImage("images/chocolat.jpg", 90, 70));

        // Charger les images pour les nappages
        Chantilly.setIcon(redimensionnerImage("images/chantilly.jpg", 110, 70));
        NappageCaramel.setIcon(redimensionnerImage("images/nappageCaramel.jpg", 110, 70));
        NappageFraise.setIcon(redimensionnerImage("images/nappageFraise.jpg", 110, 70));
        NappageChocolat.setIcon(redimensionnerImage("images/nappageChocolat.jpg", 110, 70));

        // Charger les images pour les bases (pot et cornet)
        creerPot.setIcon(redimensionnerImage("images/pot.png", 80, 80));
        creerCornet.setIcon(redimensionnerImage("images/cornet.jpg", 80, 80));
    } catch (Exception e) {
        System.out.println("Erreur lors du chargement ou redimensionnement des images : " + e.getMessage());
    }
}
}




    




