/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package glcc;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;


/**
 *
 * @author fatim
 */
public class PanierInterface extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    

    private DefaultListModel<Glace> listModel;

    private GlaceInterface glaceInterface;

public PanierInterface(GlaceInterface glaceInterface) {
    this.glaceInterface = glaceInterface;
    initComponents();
    listModel = new DefaultListModel<>();
    jList1.setModel(listModel);

    // Appliquer le Renderer pour afficher les descriptions
    jList1.setCellRenderer(new GlaceListCellRenderer());
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        retourMenu = new javax.swing.JButton();
        retirerElement = new javax.swing.JButton();
        viderPanier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        prix = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        validerCommande = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Votre commande :");

        retourMenu.setBackground(new java.awt.Color(204, 0, 0));
        retourMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retourMenu.setText("Retour au Menu");
        retourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenuActionPerformed(evt);
            }
        });

        retirerElement.setBackground(new java.awt.Color(204, 0, 0));
        retirerElement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retirerElement.setText("Retirer un élément");
        retirerElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerElementActionPerformed(evt);
            }
        });

        viderPanier.setBackground(new java.awt.Color(204, 0, 0));
        viderPanier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viderPanier.setText("Vider le panier");
        viderPanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderPanierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        prix.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        prix.setForeground(new java.awt.Color(0, 102, 0));
        prix.setText("0,0 € ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Total : ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jList1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        validerCommande.setBackground(new java.awt.Color(0, 204, 0));
        validerCommande.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        validerCommande.setText("Valider la commande");
        validerCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerCommandeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prix))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(retirerElement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viderPanier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retourMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validerCommande, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(retourMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(retirerElement, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viderPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validerCommande, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourMenuActionPerformed
   dispose();
    }//GEN-LAST:event_retourMenuActionPerformed

    private void retirerElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerElementActionPerformed
    int selectedIndex = jList1.getSelectedIndex(); // Récupère l'index de l'élément sélectionné
    if (selectedIndex != -1) { // Vérifie si un élément est sélectionné
        listModel.remove(selectedIndex); // Supprime l'élément du modèle
        double total = mettreAJourTotal(); // Recalcule le total après la suppression
        glaceInterface.mettreAJourPrixPrincipal(total); // Synchronise avec GlaceInterface
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un élément à retirer.", "Aucun élément sélectionné", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_retirerElementActionPerformed

    private void viderPanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderPanierActionPerformed
        listModel.clear(); // Supprime tous les éléments du modèle
        mettreAJourTotal(); // Réinitialise le total à 0
        javax.swing.JOptionPane.showMessageDialog(this, "Le panier a été vidé.", "Panier vidé", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_viderPanierActionPerformed

    private void validerCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerCommandeActionPerformed
        if (listModel.isEmpty()) { // Vérifie si le panier est vide
        JOptionPane.showMessageDialog(this, "Votre panier est vide. Veuillez ajouter des articles avant de valider.", "Panier vide", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Ouvre l'interface d'avis
    AvisInterface avisInterface = new AvisInterface(this);
    avisInterface.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            viderPanier(); // Vider le panier après la fermeture de l'interface
        }
    });
    avisInterface.setVisible(true);

    }//GEN-LAST:event_validerCommandeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
            GlaceInterface glaceInterface = new GlaceInterface(); // Crée l'interface principale
            PanierInterface panier = new PanierInterface(glaceInterface);  // Passe la référence à l'interface principale
            panier.setVisible(true); // Affiche l'interface panier
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<Glace> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel prix;
    private javax.swing.JButton retirerElement;
    private javax.swing.JButton retourMenu;
    private javax.swing.JButton validerCommande;
    private javax.swing.JButton viderPanier;
    // End of variables declaration//GEN-END:variables

 
 public void ajouterGlaceAuPanier(Glace glace) {
    listModel.addElement(glace); // Ajouter l'objet Glace au modèle de liste
    mettreAJourTotal(); // Mettre à jour le total
}
public double mettreAJourTotal() {
    double total = 0.0;

    // Parcourir chaque glace dans le modèle
    for (int i = 0; i < listModel.getSize(); i++) {
        Glace glace = listModel.getElementAt(i);
        total += glace.getPrix(); // Ajouter le prix de chaque glace
    }

    // Mettre à jour le label affichant le total
    prix.setText(total + " €");
    return total;
}

public void rechargerPanier() {
    // Met à jour la liste ou les données affichées dans le JList
    jList1.updateUI(); // Recharge les données visibles
}

private void viderPanier() {
    listModel.clear(); // Vide tous les éléments du modèle
    double total = mettreAJourTotal(); // Réinitialise le total dans PanierInterface
    glaceInterface.resetTotalPrix(); // Réinitialise totalPrix dans GlaceInterface
    glaceInterface.mettreAJourPrixPrincipal(total); // Met à jour l'affichage dans GlaceInterface
    JOptionPane.showMessageDialog(this, "Le panier a été vidé.", "Panier vidé", JOptionPane.INFORMATION_MESSAGE);
}


private static class GlaceListCellRenderer extends DefaultListCellRenderer {
    @Override
    public java.awt.Component getListCellRendererComponent(
            JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        // Appeler la méthode parente pour configurer les propriétés par défaut
        JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

        // Vérifier que l'objet est bien une instance de Glace
        if (value instanceof Glace) {
            Glace glace = (Glace) value;
            label.setText(glace.getDesc()); // Afficher la description
        }

        return label;
    }
}

@Override
public void dispose() {
    super.dispose();
    if (glaceInterface != null) {
        double totalPrix = mettreAJourTotal(); // Recalculez le prix total
        glaceInterface.mettreAJourPrixPrincipal(totalPrix); // Met à jour dans GlaceInterface
    }
}

public GlaceInterface getGlaceInterface() {
    return glaceInterface;
}








}